# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
timezone: America/New_York
title: Î”-Lyceum
email: aherkel09@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn. Build. Change.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://delta-lyceum.com" # the base hostname & protocol for your site
twitter_username: AveryPHerkel
github_username:  aherkel09

# Build settings
markdown: kramdown
